namespace: "ralphpy"
name: "proxmox"
version: "1.0.0"
readme: "README.md"

authors:
  - "RalphPY"

description: "Proxmox VM and template automation"

license: 
  - "MIT"

dependencies: 
  "community.proxmox": ">=1.6.0"

repository: https://github.com/ralphPY/ansible_collection_proxmox