namespace: ralphpy
name: proxmox
version: 1.0.0
readme: README.md

authors:
  - Your Name

description: Proxmox VM and template automation

license: 
  - MIT

dependencies: {}

repository: https://github.com/ralphPY/ansible_collection_proxmox