collections:
  - name: community.general
    version: ">=9.0.0" # This contains the modern Proxmox modules
  - name: community.proxmox
    source: https://github.com/ansible-collections/community.proxmox.git
    type: git
    version: main