- name: Clone VMs
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    validate_certs: "{{ validate_certs }}"
    node: "{{ proxmox_node }}"
    clone: "{{ template_name }}"
    storage: "{{ storage }}"
    vmid: "{{ template_vmid }}"
    newid: "{{ item.vmid }}"
    name: "{{ item.name }}"
    full: "{{ vm_full_clone }}"
    memory: "{{ item.memory | default(omit) }}"
    cores: "{{ item.cores | default(omit) }}"
    timeout: 300
    state: present
  loop: "{{ vm_list }}"