- name: Configure network (DHCP or static)
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    validate_certs: {{ validate_certs }}
    node: "{{ node }}"
    vmid: "{{ item.vmid }}"
    ipconfig:
      ipconfig0: >-
        {{ item.ip | default('ip=dhcp') }}
    update: true
  loop: "{{ vm_list }}"