- name: Start VMs
  when: vm_start
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    validate_certs: "{{ validate_certs }}"
    node: "{{ item.node | default(proxmox_node) }}"
    vmid: "{{ item.vmid }}"
    state: started
  loop: "{{ vm_list }}"

# - name: Pause for 10 seconds
#   ansible.builtin.pause:
#     seconds: 10

# - name: Restart VMs
#   when: vm_start
#   community.proxmox.proxmox_kvm:
#     api_host: "{{ proxmox_host }}"
#     api_user: "{{ proxmox_user }}"
#     api_token_id: "{{ proxmox_token_id }}"
#     api_token_secret: "{{ proxmox_token_secret }}"
#     validate_certs: "{{ validate_certs }}"
#     node: "{{ proxmox_node }}"
#     vmid: "{{ item.vmid }}"
#     state: restarted
#     force: true
#   loop: "{{ vm_list }}"