# Can be overridden in playbook
image_url: "{{ template_image_url | default('https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2') }}"
image_file: "{{ template_image_file | default('/var/lib/vz/images/debian.qcow2') }}"

template_memory: 2048
template_cores: 2
template_cpu: host
template_bridge: vmbr0
template_ipconfig: "ip={{ template_ip | default('') }}{{ template_cidr | default('') }},gw={{ template_gw | default('') }}"

validate_certs: "{{ proxmox_validate_certs | default(false) }}"

storage: "{{ proxmox_storage | default('local-lvm') }}"
ciuser: "{{ ansible_user_id | default('ansible') }}"
ciuser_pub_key: "{{ ansible_pub_key }}"

cloudinit: true
force_recreate_template: false