- name: Convert to template
  when: not template_exists or force_recreate_template
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs | default(false) }}"
    node: "{{ node }}"
    vmid: "{{ template_vmid }}"
    template: true