# - name: Check if template exists
#   delegate_to: "{{ proxmox_host }}"
#   command: qm status {{ template_vmid }}
#   register: template_status
#   failed_when: false
#   changed_when: false

#   set_fact:
#     template_exists: "{{ template_status.rc == 0 }}"         # when using cli command


- name: Check if template exists
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs | default(false) }}"
    vmid: "{{ template_vmid }}"
    node: "{{ proxmox_node }}"
    state: current
  register: template_status
  failed_when: false
  changed_when: false

- name: Set template exists fact
  set_fact:
    template_exists: "{{ template_status.failed == false }}"  # when using proxmox module

- name: Debug template status
  debug:
    msg: |-
      "Template API call failed: {{ template_status.failed }}"
      "Template API call msg: {{ template_status.msg }}"
      "Template API call status: {{ template_status.status }}"
      "Template status: {{ template_status }}"
      "Template exists: {{ template_exists }}"

# - name: Check if template exists via Proxmox API
#   uri:
#     url: "https://{{ proxmox_host }}:8006/api2/json/nodes/{{ node }}/qemu/{{ template_vmid }}/status/current"
#     method: GET
#     headers:
#       Authorization: "PVEAPIToken={{ proxmox_user }}!{{ proxmox_token_id }}={{ proxmox_token_secret }}"
#     validate_certs: false
#     status_code: [200, 404]
#   register: template_status
#   changed_when: false

#   set_fact:
#     template_exists: "{{ template_status.status == 200 }}"   # when using API call

- name: Make sure Templated is not running
  when: template_exists and force_recreate_template
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs | default(false) }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ template_vmid }}"
    state: stopped

- name: Destroy template if forced
  when: template_exists and force_recreate_template
  delegate_to: "{{ proxmox_host }}"
  become: true
  command: qm destroy {{ template_vmid }}
  delay: 5  ## Give PVE some time to fully processed the destroy action before proceeding

- name: Download image
  when: not template_exists or force_recreate_template
  delegate_to: "{{ proxmox_host }}"
  become: true
  get_url:
    url: "{{ image_url }}"
    dest: "{{ image_file }}"

- name: Create VM
  when: not template_exists or force_recreate_template
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs | default(false) }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ template_vmid }}"
    name: "{{ template_name }}"
    memory: "{{ template_memory }}"
    cores: "{{ template_cores }}"
    cpu: "{{ template_cpu }}"
    scsihw: virtio-scsi-pci
    net:
      net0: "virtio,bridge={{ template_bridge }}"
    serial:
      serial0: socket
    vga: serial0
    agent: 1
    state: present

- name: Import disk
  when: not template_exists or force_recreate_template
  delegate_to: "{{ proxmox_host }}"
  become: true
  command: qm importdisk {{ template_vmid }} {{ image_file }} {{ storage }}

- name: Attach disk
  when: not template_exists or force_recreate_template
  delegate_to: "{{ proxmox_host }}"
  become: true
  command: >
    qm set {{ template_vmid }}
    --scsi0 {{ storage }}:vm-{{ template_vmid }}-disk-0

- name: Set boot order
  when: not template_exists or force_recreate_template
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs | default(false) }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ template_vmid }}"
    boot: "order=scsi0"
    update: true

- name: Add cloud-init disk (small virtual CD_ROM)
  when: not template_exists or force_recreate_template
  delegate_to: "{{ proxmox_host }}"
  become: true
  command: >
    qm set {{ template_vmid }}
    --ide2 {{ storage }}:cloudinit
