## Start Template, modify it and stop it.
- name: Add template_ip to inventory
  ## Some modules like the package module require the host to be in inventory
  ## They do not seem to work delegating to ip address directly.
  ansible.builtin.add_host:
    name: template_vm
    ansible_host: "{{ template_ip }}"

- name: Start Template
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    validate_certs: "{{ proxmox_validate_certs | default(false) }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ template_vmid }}"
    state: started

- name: Wait for SSH to become reachable
  ansible.builtin.wait_for:
    host: "{{ template_ip }}"   ## Needs to be IP address, not hostname.
    port: 22
    connect_timeout: 10
    delay: 10
    timeout: 600

- name: Wait for cloud-init to finish on remote host (rc2 is OK, as it only indicates deprication warnings)
  ansible.builtin.shell: cloud-init status --wait
  args:
    executable: /bin/bash
  delegate_to: template_vm
  retries: 3
  delay: 10
  #until: cloud_init_status is succeeded
  until: "'status: done' in cloud_init_status.stdout"
  ignore_errors: true
  changed_when: false
  register: cloud_init_status

- name: Debug cloud-init status
  debug:
    msg: |-
      "Template cloud-init status: {{ cloud_init_status.msg }}"
      "Template cloud-init stdout: {{ cloud_init_status.stdout }}"
      "Template cloud-init stderr: {{ cloud_init_status.stderr }}"
      "Template cloud-init rc: {{ cloud_init_status.rc }}"
      "Template cloud-init failed: {{ cloud_init_status.failed }}"

- name: update sshd config
  delegate_to: "{{ template_ip }}"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication no'
    line: 'PasswordAuthentication yes'
  notify: Restart SSH           ## Run handler to restart SSH after modifying the config

- name: Wait for SSH to become reachable
  ansible.builtin.wait_for:
    host: "{{ template_ip }}"   ## Needs to be IP address, not hostname.
    port: 22
    connect_timeout: 10
    delay: 10
    timeout: 600

# - name: Debug template_ip
#   ansible.builtin.debug:
#     var: template_ip

# - name: Dummy task to populate hostvars
#   ansible.builtin.ping:
#   delegate_to: my_vm

- name: Ensure qemu-guest-agent is installed
  delegate_to: template_vm
  become: true
  ansible.builtin.package:
    name:  qemu-guest-agent
    state: present


