- name: Validate required variables
  assert:
    that:
      - proxmox_host is defined
      - proxmox_user is defined
      - proxmox_token_id is defined
      - proxmox_token_secret is defined
      - proxmox_node is defined
      - validate_certs is defined
      - storage is defined
      - template_vmid is defined
      - template_name is defined
      - ciuser is defined
      - ciuser_pub_key is defined
    fail_msg: "Missing required Proxmox variables"